In [1]:
import numpy as np
import pandas as pd
import QUANTAXIS as qa

QUANTAXIS>> start QUANTAXIS
QUANTAXIS>> Welcome to QUANTAXIS, the Version is 1.0.65
QUANTAXIS>>
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``########`````##````````##``````````##`````````####````````##```##########````````#``````##``````###```##`````######``
  `##``````## ```##````````##`````````####````````##`##```````##```````##```````````###``````##````##`````##```##`````##`
  ##````````##```##````````##````````##`##````````##``##``````##```````##``````````####```````#```##``````##```##``````##
  ##````````##```##````````##```````##```##```````##```##`````##```````##`````````##`##```````##`##```````##````##```````
  ##````````##```##````````##``````##`````##``````##````##````##```````##````````##``###```````###````````##`````##``````
  ##````````##```##````````##``````##``````##`````##`````##```##```````##```````##````##```````###````````##``````###````
  ##````````##```##````````##`````##````````##````##``````##``##```````##``````##``````##`````##`##```````##````````##```
  ##````````##```##````````##````#############````##```````##`##```````##`````###########`````##``##``````##`````````##``
  ###```````##```##````````##```##```````````##```##```````##`##```````##````##`````````##```##```##``````##```##`````##`
  `##``````###````##``````###``##`````````````##``##````````####```````##```##``````````##``###````##`````##````##`````##
  ``#########``````########```##``````````````###`##``````````##```````##``##````````````##`##``````##````##`````###``###
  ````````#####`````````````````````````````````````````````````````````````````````````````````````````````````````##``
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``````````````````````````Copyright``yutiansut``2018``````QUANTITATIVE FINANCIAL FRAMEWORK`````````````````````````````
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

In [2]:
stocks = qa.QA_fetch_stock_list_adv().code.tolist()[:100]
candles = qa.QA_fetch_stock_day_adv(stocks, start = '2018-01-01', end='2018-07-14').to_qfq()
candles.data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11463 entries, (2018-01-02 00:00:00, 000001) to (2018-07-13 00:00:00, 000488)
Data columns (total 10 columns):
code        11463 non-null object
open        11463 non-null float64
high        11463 non-null float64
low         11463 non-null float64
close       11463 non-null float64
volume      11463 non-null float64
amount      11463 non-null float64
date        11463 non-null datetime64[ns]
preclose    11364 non-null float64
adj         11463 non-null float64
dtypes: datetime64[ns](1), float64(8), object(1)
memory usage: 931.0+ KB

In [3]:
candles.data.head(10)

                     code       open       high        low      close  \
date       code
2018-01-02 000001  000001  13.143212  13.714228  13.113677  13.487790
           000002  000002  31.450000  32.990000  31.450000  32.560000
           000004  000004  22.290000  22.490000  22.000000  22.340000
           000005  000005   4.150000   4.500000   4.150000   4.320000
           000008  000008   8.750000   8.820000   8.700000   8.770000
           000009  000009   7.270000   7.330000   7.230000   7.320000
           000010  000010   5.380000   5.490000   5.330000   5.480000
           000011  000011  16.403913  16.763904  16.345537  16.617962
           000012  000012   7.189112   7.516673   7.180491   7.430473
           000014  000014  10.772682  11.042498  10.742702  10.912587

                         volume        amount       date  preclose       adj
date       code
2018-01-02 000001  2.114343e+06  2.856544e+09 2018-01-02       NaN  0.984510
           000002  6.834330e+05  2.218503e+09 2018-01-02       NaN  1.000000
           000004  6.261000e+03  1.395100e+07 2018-01-02       NaN  1.000000
           000005  7.153900e+04  3.052976e+07 2018-01-02       NaN  1.000000
           000008  8.289900e+04  7.252324e+07 2018-01-02       NaN  1.000000
           000009  1.926990e+05  1.404975e+08 2018-01-02       NaN  1.000000
           000010  8.519800e+04  4.622510e+07 2018-01-02       NaN  1.000000
           000011  4.700043e+04  7.823395e+07 2018-01-02       NaN  0.972949
           000012  4.436465e+05  3.273591e+08 2018-01-02       NaN  0.862004
           000014  3.243202e+04  3.541512e+07 2018-01-02       NaN  0.999321

In [5]:
ca = qa.QA_fetch_stock_day_adv('000001',  start = '2018-01-01', end='2018-07-14').to_qfq().data
ca['s1'] = ca.open / ca.preclose - 1
ca['s2'] = ca.close / ca.open - 1
ca.tail(20)

,,code,open,high,low,close,volume,amount,date,preclose,adj,s1,s2
date,code,,,,,,,,,,,,
2018-06-15,000001,000001,9.923863,10.130610,9.904173,10.012469,1.268353e+06,1.273413e+09,2018-06-15,9.914018,0.98451,0.000993,0.008929
2018-06-19,000001,000001,9.894328,9.992779,9.667891,9.717116,1.590511e+06,1.565757e+09,2018-06-19,10.012469,0.98451,-0.011799,-0.017910
2018-06-20,000001,000001,9.717116,9.795877,9.608820,9.756497,7.756516e+05,7.529507e+08,2018-06-20,9.717116,0.98451,0.000000,0.004053
2018-06-21,000001,000001,9.776187,9.884483,9.707271,9.707271,8.532872e+05,8.360148e+08,2018-06-21,9.756497,0.98451,0.002018,-0.007049
2018-06-22,000001,000001,9.648200,9.717116,9.618665,9.697426,6.681678e+05,6.457529e+08,2018-06-22,9.707271,0.98451,-0.006085,0.005102
2018-06-25,000001,000001,9.756497,9.766342,9.234706,9.313467,1.214017e+06,1.154559e+09,2018-06-25,9.697426,0.98451,0.006091,-0.045409
2018-06-26,000001,000001,9.244551,9.293777,8.949198,9.215016,1.141844e+06,1.042529e+09,2018-06-26,9.313467,0.98451,-0.007400,-0.003195
2018-06-27,000001,000001,9.165790,9.254396,8.890128,8.949198,1.061586e+06,9.588717e+08,2018-06-27,9.215016,0.98451,-0.005342,-0.023631
2018-06-28,000001,000001,8.811367,8.939353,8.732606,8.781831,1.128240e+06,9.968012e+08,2018-06-28,8.949198,0.98451,-0.015402,-0.003352
2018-06-29,000001,000001,8.870437,8.988579,8.821212,8.949198,6.859238e+05,6.113461e+08,2018-06-29,8.781831,0.98451,0.010090,0.008879
2018-07-02,000001,000001,8.909818,8.909818,8.417563,8.476633,1.336218e+06,1.158546e+09,2018-07-02,8.949198,0.98451,-0.004400,-0.048619
2018-07-03,000001,000001,8.555394,8.565239,8.319112,8.535704,1.294896e+06,1.096657e+09,2018-07-03,8.476633,0.98451,0.009292,-0.002301
2018-07-04,000001,000001,8.496323,8.614465,8.476633,8.476633,7.223419e+05,6.172785e+08,2018-07-04,8.535704,0.98451,-0.004614,-0.002317
2018-07-05,000001,000001,8.486478,8.594774,8.417563,8.466788,8.489175e+05,7.221696e+08,2018-07-05,8.476633,0.98451,0.001161,-0.002320
2018-07-06,000001,000001,8.476633,8.644000,8.319112,8.525859,1.003831e+06,8.520716e+08,2018-07-06,8.466788,0.98451,0.001163,0.005807
2018-07-09,000001,000001,8.555394,8.890128,8.545549,8.890128,1.432137e+06,1.255008e+09,2018-07-09,8.525859,0.98451,0.003464,0.039125
2018-07-10,000001,000001,8.880282,8.880282,8.752296,8.840902,9.109727e+05,8.030390e+08,2018-07-10,8.890128,0.98451,-0.001107,-0.004435
2018-07-11,000001,000001,8.624310,8.693226,8.545549,8.644000,8.646898e+05,7.447658e+08,2018-07-11,8.840902,0.98451,-0.024499,0.002283
2018-07-12,000001,000001,8.600000,8.970000,8.580000,8.880000,1.140492e+06,1.008659e+09,2018-07-12,8.644000,1.00000,-0.005090,0.032558
2018-07-13,000001,000001,8.920000,8.940000,8.820000,8.880000,6.033780e+05,5.354012e+08,2018-07-13,8.880000,1.00000,0.004505,-0.004484

In [6]:
ca.loc[:, ['s1', 's2']].stack().tail(20)

date        code
2018-07-02  000001  s1   -0.004400
                    s2   -0.048619
2018-07-03  000001  s1    0.009292
                    s2   -0.002301
2018-07-04  000001  s1   -0.004614
                    s2   -0.002317
2018-07-05  000001  s1    0.001161
                    s2   -0.002320
2018-07-06  000001  s1    0.001163
                    s2    0.005807
2018-07-09  000001  s1    0.003464
                    s2    0.039125
2018-07-10  000001  s1   -0.001107
                    s2   -0.004435
2018-07-11  000001  s1   -0.024499
                    s2    0.002283
2018-07-12  000001  s1   -0.005090
                    s2    0.032558
2018-07-13  000001  s1    0.004505
                    s2   -0.004484
dtype: float64

In [7]:
days = ca.loc[:, ['s1', 's2']].stack()
type(days)

pandas.core.series.Series

In [9]:
days.name = '000001'
days.reset_index(level=1, drop=True).tail(30)

date
2018-06-25  s1    0.006091
            s2   -0.045409
2018-06-26  s1   -0.007400
            s2   -0.003195
2018-06-27  s1   -0.005342
            s2   -0.023631
2018-06-28  s1   -0.015402
            s2   -0.003352
2018-06-29  s1    0.010090
            s2    0.008879
2018-07-02  s1   -0.004400
            s2   -0.048619
2018-07-03  s1    0.009292
            s2   -0.002301
2018-07-04  s1   -0.004614
            s2   -0.002317
2018-07-05  s1    0.001161
            s2   -0.002320
2018-07-06  s1    0.001163
            s2    0.005807
2018-07-09  s1    0.003464
            s2    0.039125
2018-07-10  s1   -0.001107
            s2   -0.004435
2018-07-11  s1   -0.024499
            s2    0.002283
2018-07-12  s1   -0.005090
            s2    0.032558
2018-07-13  s1    0.004505
            s2   -0.004484
Name: 000001, dtype: float64

In [10]:
pd.concat([days, days], axis=1)

                            000001        000001
date       code
2018-01-02 000001 s2  2.621723e-02  2.621723e-02
2018-01-03 000001 s1  2.189781e-03  2.189781e-03
                  s2 -2.913328e-02 -2.913328e-02
2018-01-04 000001 s1 -7.501875e-04 -7.501875e-04
                  s2 -5.255255e-03 -5.255255e-03
2018-01-05 000001 s1 -3.018868e-03 -3.018868e-03
                  s2  6.813020e-03  6.813020e-03
2018-01-08 000001 s1 -3.759398e-03 -3.759398e-03
                  s2 -2.188679e-02 -2.188679e-02
2018-01-09 000001 s1 -1.110223e-16 -1.110223e-16
                  s2  9.259259e-03  9.259259e-03
2018-01-10 000001 s1 -3.058104e-03 -3.058104e-03
                  s2  3.297546e-02  3.297546e-02
2018-01-11 000001 s1 -4.454343e-03 -4.454343e-03
                  s2 -7.457122e-04 -7.457122e-04
2018-01-12 000001 s1  3.731343e-03  3.731343e-03
                  s2  7.434944e-03  7.434944e-03
2018-01-15 000001 s1 -2.952030e-03 -2.952030e-03
                  s2  5.107328e-02  5.107328e-02
2018-01-16 000001 s1 -2.112676e-03 -2.112676e-03
                  s2  2.117149e-03  2.117149e-03
2018-01-17 000001 s1  9.154930e-03  9.154930e-03
                  s2 -6.978367e-03 -6.978367e-03
2018-01-18 000001 s1  1.194659e-02  1.194659e-02
                  s2  2.222222e-02  2.222222e-02
2018-01-19 000001 s1  5.434783e-03  5.434783e-03
                  s2  0.000000e+00  0.000000e+00
2018-01-22 000001 s1 -1.351351e-02 -1.351351e-02
                  s2 -1.095890e-02 -1.095890e-02
2018-01-23 000001 s1 -5.540166e-03 -5.540166e-03
...                            ...           ...
2018-06-25 000001 s1  6.091371e-03  6.091371e-03
                  s2 -4.540868e-02 -4.540868e-02
2018-06-26 000001 s1 -7.399577e-03 -7.399577e-03
                  s2 -3.194888e-03 -3.194888e-03
2018-06-27 000001 s1 -5.341880e-03 -5.341880e-03
                  s2 -2.363050e-02 -2.363050e-02
2018-06-28 000001 s1 -1.540154e-02 -1.540154e-02
                  s2 -3.351955e-03 -3.351955e-03
2018-06-29 000001 s1  1.008969e-02  1.008969e-02
                  s2  8.879023e-03  8.879023e-03
2018-07-02 000001 s1 -4.400440e-03 -4.400440e-03
                  s2 -4.861878e-02 -4.861878e-02
2018-07-03 000001 s1  9.291521e-03  9.291521e-03
                  s2 -2.301496e-03 -2.301496e-03
2018-07-04 000001 s1 -4.613610e-03 -4.613610e-03
                  s2 -2.317497e-03 -2.317497e-03
2018-07-05 000001 s1  1.161440e-03  1.161440e-03
                  s2 -2.320186e-03 -2.320186e-03
2018-07-06 000001 s1  1.162791e-03  1.162791e-03
                  s2  5.807201e-03  5.807201e-03
2018-07-09 000001 s1  3.464203e-03  3.464203e-03
                  s2  3.912543e-02  3.912543e-02
2018-07-10 000001 s1 -1.107420e-03 -1.107420e-03
                  s2 -4.434590e-03 -4.434590e-03
2018-07-11 000001 s1 -2.449889e-02 -2.449889e-02
                  s2  2.283105e-03  2.283105e-03
2018-07-12 000001 s1 -5.090236e-03 -5.090236e-03
                  s2  3.255814e-02  3.255814e-02
2018-07-13 000001 s1  4.504505e-03  4.504505e-03
                  s2 -4.484305e-03 -4.484305e-03

[257 rows x 2 columns]

In [11]:
def prepare_days(stock):
    ca = qa.QA_fetch_stock_day_adv(stock,  start = '2018-01-01', end='2018-07-14').to_qfq().data
    ca['s1'] = ca.open / ca.preclose - 1
    ca['s2'] = ca.close / ca.open - 1
    days = ca.loc[:, ['s1', 's2']].stack()
    days.name = stock
    return days.reset_index(level=1, drop=True)

In [13]:
full = pd.concat([prepare_days(x) for x in stocks[:10]], axis=1).reset_index(level=1, drop=True).fillna(0)
full.tail(30)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011
date,,,,,,,,,,
2018-06-25,0.006091,0.005338,0.001576,0.000000,0.011686,0.000000,0.0,0.012397,0.017456,0.015776
2018-06-25,-0.045409,-0.062301,-0.011018,0.000000,-0.016502,0.000000,0.0,-0.014286,-0.019608,-0.015531
2018-06-26,-0.007400,-0.025293,-0.006897,-0.006826,-0.016779,0.000000,0.0,-0.008282,-0.007500,-0.013146
2018-06-26,-0.003195,-0.010844,0.006944,0.013746,0.008532,0.000000,0.0,0.018789,0.012594,-0.000888
2018-06-27,-0.005342,-0.001566,0.002653,-0.003390,-0.001692,0.000000,0.0,-0.002049,0.002488,0.002667
2018-06-27,-0.023631,-0.050196,-0.000529,0.003401,-0.020339,0.000000,0.0,-0.012320,-0.054591,-0.000887
2018-06-28,-0.015402,-0.014864,0.000000,0.000000,-0.003460,0.000000,0.0,0.000000,-0.028871,-0.015084
2018-06-28,-0.003352,0.000838,0.007411,-0.016949,-0.010417,0.000000,0.0,-0.008316,0.048649,-0.000901
2018-06-29,0.010090,0.009213,-0.005780,0.000000,0.003509,-0.008053,0.0,0.002096,-0.015464,0.000927
2018-06-29,0.008879,0.020747,0.035941,0.020690,0.024476,-0.011808,0.0,0.025105,0.023560,0.025000
2018-07-02,-0.004400,-0.004065,-0.001020,0.003378,-0.005119,-0.017177,0.0,0.000000,0.010230,-0.002710
2018-07-02,-0.048619,-0.069388,-0.024515,-0.023569,-0.056604,0.007599,0.0,-0.024490,-0.020253,-0.045290
2018-07-03,0.009292,0.013158,0.010995,-0.003448,0.005455,-0.013575,0.0,0.000000,0.000000,0.000000
2018-07-03,-0.002301,0.013853,0.002071,0.013841,0.021700,0.025229,0.0,0.020921,0.020672,-0.009488
2018-07-04,-0.004614,0.001708,0.000517,0.000000,-0.007080,0.000746,0.0,-0.004098,0.000000,-0.006705
2018-07-04,-0.002317,-0.019608,-0.007748,0.000000,0.016043,-0.002981,0.0,-0.014403,0.005063,0.043394
2018-07-05,0.001161,0.000870,0.002603,0.000000,-0.008772,0.000000,0.0,0.014614,0.025189,-0.014787
2018-07-05,-0.002320,0.001303,-0.009346,-0.023891,-0.051327,-0.007474,0.0,-0.028807,-0.049140,-0.050657
2018-07-06,0.001163,0.012581,-0.005241,0.010490,0.007463,0.009036,0.0,0.004237,0.007752,0.007905
2018-07-06,0.005807,-0.005570,0.003161,-0.006920,-0.014815,0.000746,0.0,-0.004219,0.015385,-0.002941
2018-07-09,0.003464,0.006894,0.000000,0.000000,0.001880,-0.000746,0.0,0.000000,0.012626,0.002950
2018-07-09,0.039125,0.027386,-0.010504,0.010453,0.016886,0.010448,0.0,0.029661,0.002494,0.006863
2018-07-10,-0.001107,0.007913,-0.002123,0.003448,0.005535,-0.002954,0.0,0.006173,-0.014925,0.011685
2018-07-10,-0.004435,-0.002066,-0.003191,0.000000,0.009174,0.029630,0.0,0.000000,0.047980,0.008662
2018-07-11,-0.024499,-0.027743,-0.006937,-0.003436,-0.016364,-0.009353,0.0,-0.006135,0.014458,-0.024809
2018-07-11,0.002283,-0.000852,0.008598,-0.024138,-0.016636,-0.018155,0.0,-0.014403,-0.009501,-0.018591
2018-07-12,-0.005090,0.005115,-0.001598,0.003534,-0.005639,0.004438,0.0,-0.002088,0.014388,-0.001994
2018-07-12,0.032558,0.011450,0.017076,0.017606,0.034026,-0.002209,0.0,0.025105,0.070922,0.025974
2018-07-13,0.004505,0.016352,0.004197,0.003460,0.020110,0.000738,0.0,0.002041,-0.017660,0.001947
2018-07-13,-0.004484,-0.021452,-0.020376,0.013793,-0.010753,0.054572,0.0,0.004073,0.044944,-0.000972

In [15]:
cor =full.corr()
cor

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011
000001,1.000000,0.608419,0.003288,0.172173,0.293589,0.039020,0.083113,0.170158,0.048050,0.311012
000002,0.608419,1.000000,0.062661,0.207038,0.316695,0.146088,0.094837,0.224898,0.141725,0.406875
000004,0.003288,0.062661,1.000000,0.144979,0.232859,0.072712,0.067868,0.310509,0.292273,0.246391
000005,0.172173,0.207038,0.144979,1.000000,0.494253,0.118530,0.066302,0.540138,0.261294,0.557927
000006,0.293589,0.316695,0.232859,0.494253,1.000000,0.220992,0.050770,0.464935,0.294281,0.563745
000007,0.039020,0.146088,0.072712,0.118530,0.220992,1.000000,0.014604,0.139099,0.162213,0.046024
000008,0.083113,0.094837,0.067868,0.066302,0.050770,0.014604,1.000000,0.142208,0.098237,0.113160
000009,0.170158,0.224898,0.310509,0.540138,0.464935,0.139099,0.142208,1.000000,0.308649,0.537702
000010,0.048050,0.141725,0.292273,0.261294,0.294281,0.162213,0.098237,0.308649,1.000000,0.258220
000011,0.311012,0.406875,0.246391,0.557927,0.563745,0.046024,0.113160,0.537702,0.258220,1.000000

In [46]:
cc = cor.stack().reset_index()
cc['rr'] = cc.groupby('level_0')[0].transform(pd.DataFrame.rank, ascending=False)
cc

   level_0 level_1         0    rr
0   000001  000001  1.000000   1.0
1   000001  000002  0.608419   2.0
2   000001  000004  0.003288  10.0
3   000001  000005  0.172173   5.0
4   000001  000006  0.293589   4.0
5   000001  000007  0.039020   9.0
6   000001  000008  0.083113   7.0
7   000001  000009  0.170158   6.0
8   000001  000010  0.048050   8.0
9   000001  000011  0.311012   3.0
10  000002  000001  0.608419   2.0
11  000002  000002  1.000000   1.0
12  000002  000004  0.062661  10.0
13  000002  000005  0.207038   6.0
14  000002  000006  0.316695   4.0
15  000002  000007  0.146088   7.0
16  000002  000008  0.094837   9.0
17  000002  000009  0.224898   5.0
18  000002  000010  0.141725   8.0
19  000002  000011  0.406875   3.0
20  000004  000001  0.003288  10.0
21  000004  000002  0.062661   9.0
22  000004  000004  1.000000   1.0
23  000004  000005  0.144979   6.0
24  000004  000006  0.232859   5.0
25  000004  000007  0.072712   7.0
26  000004  000008  0.067868   8.0
27  000004  000009  0.310509   2.0
28  000004  000010  0.292273   3.0
29  000004  000011  0.246391   4.0
..     ...     ...       ...   ...
70  000009  000001  0.170158   8.0
71  000009  000002  0.224898   7.0
72  000009  000004  0.310509   5.0
73  000009  000005  0.540138   2.0
74  000009  000006  0.464935   4.0
75  000009  000007  0.139099  10.0
76  000009  000008  0.142208   9.0
77  000009  000009  1.000000   1.0
78  000009  000010  0.308649   6.0
79  000009  000011  0.537702   3.0
80  000010  000001  0.048050  10.0
81  000010  000002  0.141725   8.0
82  000010  000004  0.292273   4.0
83  000010  000005  0.261294   5.0
84  000010  000006  0.294281   3.0
85  000010  000007  0.162213   7.0
86  000010  000008  0.098237   9.0
87  000010  000009  0.308649   2.0
88  000010  000010  1.000000   1.0
89  000010  000011  0.258220   6.0
90  000011  000001  0.311012   6.0
91  000011  000002  0.406875   5.0
92  000011  000004  0.246391   8.0
93  000011  000005  0.557927   3.0
94  000011  000006  0.563745   2.0
95  000011  000007  0.046024  10.0
96  000011  000008  0.113160   9.0
97  000011  000009  0.537702   4.0
98  000011  000010  0.258220   7.0
99  000011  000011  1.000000   1.0

[100 rows x 4 columns]

In [ ]:
cc['rr'] = pd.rank

In [28]:
cdict = {}

In [36]:
def insert(x):
    y = x.values
    if y[0]<y[1]:
        cdict['{}_{}'.format(y[0], y[1])] = y[2]
    return 0
    
cc.apply(insert, axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
     ..
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [37]:
cdict

{'000001_000002': 0.6084189627028531,
 '000001_000004': 0.003287934001707852,
 '000001_000005': 0.17217338909717783,
 '000001_000006': 0.29358921683869654,
 '000001_000007': 0.03902023123806128,
 '000001_000008': 0.08311299082787685,
 '000001_000009': 0.17015753911142117,
 '000001_000010': 0.04804998453976293,
 '000001_000011': 0.3110123570496493,
 '000002_000004': 0.06266134577651837,
 '000002_000005': 0.2070381474834291,
 '000002_000006': 0.3166947387133915,
 '000002_000007': 0.14608778657035193,
 '000002_000008': 0.09483709145087155,
 '000002_000009': 0.22489783925927778,
 '000002_000010': 0.14172548225077164,
 '000002_000011': 0.4068746092347338,
 '000004_000005': 0.14497854771005816,
 '000004_000006': 0.23285884352689434,
 '000004_000007': 0.07271247539136017,
 '000004_000008': 0.06786800302971253,
 '000004_000009': 0.3105085122254936,
 '000004_000010': 0.29227254545250164,
 '000004_000011': 0.24639066379278307,
 '000005_000006': 0.4942529141013744,
 '000005_000007': 0.1185304431722458,
 '000005_000008': 0.06630201622973236,
 '000005_000009': 0.5401380991972762,
 '000005_000010': 0.2612940965745833,
 '000005_000011': 0.5579266801688852,
 '000006_000007': 0.22099184649522272,
 '000006_000008': 0.050769959509747525,
 '000006_000009': 0.464934932839733,
 '000006_000010': 0.29428139640348505,
 '000006_000011': 0.5637452435883524,
 '000007_000008': 0.014603553907872765,
 '000007_000009': 0.13909897980285607,
 '000007_000010': 0.16221292790365846,
 '000007_000011': 0.04602448671179809,
 '000008_000009': 0.14220810111210433,
 '000008_000010': 0.0982372216962494,
 '000008_000011': 0.11316025648729473,
 '000009_000010': 0.30864945553174167,
 '000009_000011': 0.5377017216560455,
 '000010_000011': 0.25821976477823205}

In [47]:
da = qa.QA_fetch_stock_day_adv('000011',  start = '2018-01-01', end='2018-07-14').to_qfq().data
da.tail(10)

,,code,open,high,low,close,volume,amount,date,preclose,adj
date,code,,,,,,,,,,
2018-07-02,000011,000011,11.04,11.04,10.30,10.54,29985.0,32272008.0,2018-07-02,11.07,1.0
2018-07-03,000011,000011,10.54,10.64,10.05,10.44,39084.0,40264464.0,2018-07-03,10.54,1.0
2018-07-04,000011,000011,10.37,11.31,10.25,10.82,60978.0,65974584.0,2018-07-04,10.44,1.0
2018-07-05,000011,000011,10.66,10.71,10.05,10.12,38814.0,40233724.0,2018-07-05,10.82,1.0
2018-07-06,000011,000011,10.20,10.30,9.69,10.17,39045.0,39174432.0,2018-07-06,10.12,1.0
2018-07-09,000011,000011,10.20,10.32,10.10,10.27,20782.0,21289630.0,2018-07-09,10.17,1.0
2018-07-10,000011,000011,10.39,10.48,10.26,10.48,25050.0,26055166.0,2018-07-10,10.27,1.0
2018-07-11,000011,000011,10.22,10.22,9.83,10.03,26031.0,26036030.0,2018-07-11,10.48,1.0
2018-07-12,000011,000011,10.01,10.34,10.01,10.27,23620.0,24168698.0,2018-07-12,10.03,1.0
2018-07-13,000011,000011,10.29,10.48,10.24,10.28,21998.0,22755630.0,2018-07-13,10.27,1.0