In [1]:
import QUANTAXIS as qa
import numpy as np
import pandas as pd

QUANTAXIS>> start QUANTAXIS
QUANTAXIS>> Welcome to QUANTAXIS, the Version is 1.0.55
QUANTAXIS>>
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``########`````##````````##``````````##`````````####````````##```##########````````#``````##``````###```##`````######``
  `##``````## ```##````````##`````````####````````##`##```````##```````##```````````###``````##````##`````##```##`````##`
  ##````````##```##````````##````````##`##````````##``##``````##```````##``````````####```````#```##``````##```##``````##
  ##````````##```##````````##```````##```##```````##```##`````##```````##`````````##`##```````##`##```````##````##```````
  ##````````##```##````````##``````##`````##``````##````##````##```````##````````##``###```````###````````##`````##``````
  ##````````##```##````````##``````##``````##`````##`````##```##```````##```````##````##```````###````````##``````###````
  ##````````##```##````````##`````##````````##````##``````##``##```````##``````##``````##`````##`##```````##````````##```
  ##````````##```##````````##````#############````##```````##`##```````##`````###########`````##``##``````##`````````##``
  ###```````##```##````````##```##```````````##```##```````##`##```````##````##`````````##```##```##``````##```##`````##`
  `##``````###````##``````###``##`````````````##``##````````####```````##```##``````````##``###````##`````##````##`````##
  ``#########``````########```##``````````````###`##``````````##```````##``##````````````##`##``````##````##`````###``###
  ````````#####`````````````````````````````````````````````````````````````````````````````````````````````````````##``
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``````````````````````````Copyright``yutiansut``2018``````QUANTITATIVE FINANCIAL FRAMEWORK`````````````````````````````
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

In [8]:
import re

In [2]:
stocks = qa.QA_fetch_stock_list_adv().code.tolist()
stocks

['000001',
 '000002',
 '000004',
 '000005',
 '000006',
 '000007',
 '000008',
 '000009',
 '000010',
 '000011',
 '000012',
 '000014',
 '000016',
 '000017',
 '000018',
 '000019',
 '000020',
 '000021',
 '000022',
 '000023',
 '000025',
 '000026',
 '000027',
 '000028',
 '000029',
 '000030',
 '000031',
 '000032',
 '000034',
 '000035',
 '000036',
 '000037',
 '000038',
 '000039',
 '000040',
 '000042',
 '000043',
 '000045',
 '000046',
 '000048',
 '000049',
 '000050',
 '000055',
 '000056',
 '000058',
 '000059',
 '000060',
 '000061',
 '000062',
 '000063',
 '000065',
 '000066',
 '000068',
 '000069',
 '000070',
 '000078',
 '000088',
 '000089',
 '000090',
 '000096',
 '000099',
 '000100',
 '000150',
 '000151',
 '000153',
 '000155',
 '000156',
 '000157',
 '000158',
 '000159',
 '000166',
 '000301',
 '000333',
 '000338',
 '000400',
 '000401',
 '000402',
 '000403',
 '000404',
 '000407',
 '000408',
 '000409',
 '000410',
 '000411',
 '000413',
 '000415',
 '000416',
 '000417',
 '000418',
 '000419',
 '000420',
 '000421',
 '000422',
 '000423',
 '000425',
 '000426',
 '000428',
 '000429',
 '000430',
 '000488',
 '000498',
 '000501',
 '000502',
 '000503',
 '000504',
 '000505',
 '000506',
 '000507',
 '000509',
 '000510',
 '000511',
 '000513',
 '000514',
 '000516',
 '000517',
 '000518',
 '000519',
 '000520',
 '000521',
 '000523',
 '000524',
 '000525',
 '000526',
 '000528',
 '000529',
 '000530',
 '000531',
 '000532',
 '000533',
 '000534',
 '000536',
 '000537',
 '000538',
 '000539',
 '000540',
 '000541',
 '000543',
 '000544',
 '000545',
 '000546',
 '000547',
 '000548',
 '000550',
 '000551',
 '000552',
 '000553',
 '000554',
 '000555',
 '000557',
 '000558',
 '000559',
 '000560',
 '000561',
 '000563',
 '000564',
 '000565',
 '000566',
 '000567',
 '000568',
 '000570',
 '000571',
 '000572',
 '000573',
 '000576',
 '000581',
 '000582',
 '000584',
 '000585',
 '000586',
 '000587',
 '000589',
 '000590',
 '000591',
 '000592',
 '000593',
 '000595',
 '000596',
 '000597',
 '000598',
 '000599',
 '000600',
 '000601',
 '000603',
 '000605',
 '000606',
 '000607',
 '000608',
 '000609',
 '000610',
 '000611',
 '000612',
 '000613',
 '000615',
 '000616',
 '000617',
 '000619',
 '000620',
 '000622',
 '000623',
 '000625',
 '000626',
 '000627',
 '000628',
 '000629',
 '000630',
 '000631',
 '000632',
 '000633',
 '000635',
 '000636',
 '000637',
 '000638',
 '000639',
 '000650',
 '000651',
 '000652',
 '000655',
 '000656',
 '000657',
 '000659',
 '000661',
 '000662',
 '000663',
 '000665',
 '000666',
 '000667',
 '000668',
 '000669',
 '000670',
 '000671',
 '000672',
 '000673',
 '000676',
 '000677',
 '000678',
 '000679',
 '000680',
 '000681',
 '000682',
 '000683',
 '000685',
 '000686',
 '000687',
 '000688',
 '000690',
 '000691',
 '000692',
 '000695',
 '000697',
 '000698',
 '000700',
 '000701',
 '000702',
 '000703',
 '000705',
 '000707',
 '000708',
 '000709',
 '000710',
 '000711',
 '000712',
 '000713',
 '000715',
 '000716',
 '000717',
 '000718',
 '000719',
 '000720',
 '000721',
 '000722',
 '000723',
 '000725',
 '000726',
 '000727',
 '000728',
 '000729',
 '000731',
 '000732',
 '000733',
 '000735',
 '000736',
 '000737',
 '000738',
 '000739',
 '000750',
 '000751',
 '000752',
 '000753',
 '000755',
 '000756',
 '000757',
 '000758',
 '000759',
 '000760',
 '000761',
 '000762',
 '000766',
 '000767',
 '000768',
 '000776',
 '000777',
 '000778',
 '000779',
 '000780',
 '000782',
 '000783',
 '000785',
 '000786',
 '000788',
 '000789',
 '000790',
 '000791',
 '000792',
 '000793',
 '000795',
 '000796',
 '000797',
 '000798',
 '000799',
 '000800',
 '000801',
 '000802',
 '000803',
 '000806',
 '000807',
 '000809',
 '000810',
 '000811',
 '000812',
 '000813',
 '000815',
 '000816',
 '000818',
 '000819',
 '000820',
 '000821',
 '000822',
 '000823',
 '000825',
 '000826',
 '000828',
 '000829',
 '000830',
 '000831',
 '000833',
 '000835',
 '000836',
 '000837',
 '000838',
 '000839',
 '000848',
 '000850',
 '000851',
 '000852',
 '000856',
 '000858',
 '000859',
 '000860',
 '000861',
 '000862',
 '000863',
 '000868',
 '000869',
 '000875',
 '000876',
 '000877',
 '000878',
 '000880',
 '000881',
 '000882',
 '000883',
 '000885',
 '000886',
 '000887',
 '000888',
 '000889',
 '000890',
 '000892',
 '000893',
 '000895',
 '000897',
 '000898',
 '000899',
 '000900',
 '000901',
 '000902',
 '000903',
 '000905',
 '000906',
 '000908',
 '000909',
 '000910',
 '000911',
 '000912',
 '000913',
 '000915',
 '000917',
 '000918',
 '000919',
 '000920',
 '000921',
 '000922',
 '000923',
 '000925',
 '000926',
 '000927',
 '000928',
 '000929',
 '000930',
 '000931',
 '000932',
 '000933',
 '000935',
 '000936',
 '000937',
 '000938',
 '000939',
 '000948',
 '000949',
 '000950',
 '000951',
 '000952',
 '000953',
 '000955',
 '000957',
 '000958',
 '000959',
 '000960',
 '000961',
 '000962',
 '000963',
 '000965',
 '000966',
 '000967',
 '000968',
 '000969',
 '000970',
 '000971',
 '000972',
 '000973',
 '000975',
 '000976',
 '000977',
 '000978',
 '000979',
 '000980',
 '000981',
 '000982',
 '000983',
 '000985',
 '000987',
 '000988',
 '000989',
 '000990',
 '000993',
 '000995',
 '000996',
 '000997',
 '000998',
 '000999',
 '001696',
 '001896',
 '001965',
 '001979',
 '002001',
 '002002',
 '002003',
 '002004',
 '002005',
 '002006',
 '002007',
 '002008',
 '002009',
 '002010',
 '002011',
 '002012',
 '002013',
 '002014',
 '002015',
 '002016',
 '002017',
 '002018',
 '002019',
 '002020',
 '002021',
 '002022',
 '002023',
 '002024',
 '002025',
 '002026',
 '002027',
 '002028',
 '002029',
 '002030',
 '002031',
 '002032',
 '002033',
 '002034',
 '002035',
 '002036',
 '002037',
 '002038',
 '002039',
 '002040',
 '002041',
 '002042',
 '002043',
 '002044',
 '002045',
 '002046',
 '002047',
 '002048',
 '002049',
 '002050',
 '002051',
 '002052',
 '002053',
 '002054',
 '002055',
 '002056',
 '002057',
 '002058',
 '002059',
 '002060',
 '002061',
 '002062',
 '002063',
 '002064',
 '002065',
 '002066',
 '002067',
 '002068',
 '002069',
 '002070',
 '002071',
 '002072',
 '002073',
 '002074',
 '002075',
 '002076',
 '002077',
 '002078',
 '002079',
 '002080',
 '002081',
 '002082',
 '002083',
 '002084',
 '002085',
 '002086',
 '002087',
 '002088',
 '002089',
 '002090',
 '002091',
 '002092',
 '002093',
 '002094',
 '002095',
 '002096',
 '002097',
 '002098',
 '002099',
 '002100',
 '002101',
 '002102',
 '002103',
 '002104',
 '002105',
 '002106',
 '002107',
 '002108',
 '002109',
 '002110',
 '002111',
 '002112',
 '002113',
 '002114',
 '002115',
 '002116',
 '002117',
 '002118',
 '002119',
 '002120',
 '002121',
 '002122',
 '002123',
 '002124',
 '002125',
 '002126',
 '002127',
 '002128',
 '002129',
 '002130',
 '002131',
 '002132',
 '002133',
 '002134',
 '002135',
 '002136',
 '002137',
 '002138',
 '002139',
 '002140',
 '002141',
 '002142',
 '002143',
 '002144',
 '002145',
 '002146',
 '002147',
 '002148',
 '002149',
 '002150',
 '002151',
 '002152',
 '002153',
 '002154',
 '002155',
 '002156',
 '002157',
 '002158',
 '002159',
 '002160',
 '002161',
 '002162',
 '002163',
 '002164',
 '002165',
 '002166',
 '002167',
 '002168',
 '002169',
 '002170',
 '002171',
 '002172',
 '002173',
 '002174',
 '002175',
 '002176',
 '002177',
 '002178',
 '002179',
 '002180',
 '002181',
 '002182',
 '002183',
 '002184',
 '002185',
 '002186',
 '002187',
 '002188',
 '002189',
 '002190',
 '002191',
 '002192',
 '002193',
 '002194',
 '002195',
 '002196',
 '002197',
 '002198',
 '002199',
 '002200',
 '002201',
 '002202',
 '002203',
 '002204',
 '002205',
 '002206',
 '002207',
 '002208',
 '002209',
 '002210',
 '002211',
 '002212',
 '002213',
 '002214',
 '002215',
 '002216',
 '002217',
 '002218',
 '002219',
 '002220',
 '002221',
 '002222',
 '002223',
 '002224',
 '002225',
 '002226',
 '002227',
 '002228',
 '002229',
 '002230',
 '002231',
 '002232',
 '002233',
 '002234',
 '002235',
 '002236',
 '002237',
 '002238',
 '002239',
 '002240',
 '002241',
 '002242',
 '002243',
 '002244',
 '002245',
 '002246',
 '002247',
 '002248',
 '002249',
 '002250',
 '002251',
 '002252',
 '002253',
 '002254',
 '002255',
 '002256',
 '002258',
 '002259',
 '002260',
 '002261',
 '002262',
 '002263',
 '002264',
 '002265',
 '002266',
 '002267',
 '002268',
 '002269',
 '002270',
 '002271',
 '002272',
 '002273',
 '002274',
 '002275',
 '002276',
 '002277',
 '002278',
 '002279',
 '002280',
 '002281',
 '002282',
 '002283',
 '002284',
 '002285',
 '002286',
 '002287',
 '002288',
 '002289',
 '002290',
 '002291',
 '002292',
 '002293',
 '002294',
 '002295',
 '002296',
 '002297',
 '002298',
 '002299',
 '002300',
 '002301',
 '002302',
 '002303',
 '002304',
 '002305',
 '002306',
 '002307',
 '002308',
 '002309',
 '002310',
 '002311',
 '002312',
 '002313',
 '002314',
 '002315',
 '002316',
 '002317',
 '002318',
 '002319',
 '002320',
 '002321',
 '002322',
 '002323',
 '002324',
 '002325',
 '002326',
 '002327',
 '002328',
 '002329',
 '002330',
 '002331',
 '002332',
 '002333',
 '002334',
 '002335',
 '002336',
 '002337',
 '002338',
 '002339',
 '002340',
 '002341',
 '002342',
 '002343',
 '002344',
 '002345',
 '002346',
 '002347',
 '002348',
 '002349',
 '002350',
 '002351',
 '002352',
 '002353',
 '002354',
 '002355',
 '002356',
 '002357',
 '002358',
 '002359',
 '002360',
 '002361',
 '002362',
 '002363',
 '002364',
 '002365',
 '002366',
 '002367',
 '002368',
 '002369',
 '002370',
 '002371',
 '002372',
 '002373',
 '002374',
 '002375',
 '002376',
 '002377',
 '002378',
 '002379',
 '002380',
 '002381',
 '002382',
 '002383',
 '002384',
 '002385',
 '002386',
 '002387',
 '002388',
 '002389',
 '002390',
 '002391',
 '002392',
 '002393',
 '002394',
 '002395',
 '002396',
 '002397',
 '002398',
 '002399',
 '002400',
 '002401',
 '002402',
 '002403',
 '002404',
 '002405',
 '002406',
 '002407',
 '002408',
 '002409',
 '002410',
 '002411',
 '002412',
 '002413',
 '002414',
 '002415',
 '002416',
 '002417',
 '002418',
 '002419',
 '002420',
 '002421',
 '002422',
 '002423',
 '002424',
 '002425',
 '002426',
 '002427',
 '002428',
 '002429',
 '002430',
 '002431',
 '002432',
 '002433',
 '002434',
 '002435',
 '002436',
 '002437',
 '002438',
 '002439',
 '002440',
 '002441',
 '002442',
 '002443',
 '002444',
 '002445',
 '002446',
 '002447',
 '002448',
 '002449',
 '002450',
 '002451',
 '002452',
 '002453',
 '002454',
 '002455',
 '002456',
 '002457',
 '002458',
 '002459',
 '002460',
 '002461',
 '002462',
 '002463',
 '002464',
 '002465',
 '002466',
 '002467',
 '002468',
 '002469',
 '002470',
 '002471',
 '002472',
 '002473',
 '002474',
 '002475',
 '002476',
 '002477',
 '002478',
 '002479',
 '002480',
 '002481',
 '002482',
 '002483',
 '002484',
 '002485',
 '002486',
 '002487',
 '002488',
 '002489',
 '002490',
 '002491',
 '002492',
 '002493',
 '002494',
 '002495',
 '002496',
 '002497',
 '002498',
 '002499',
 '002500',
 '002501',
 '002502',
 '002503',
 '002504',
 '002505',
 '002506',
 '002507',
 '002508',
 '002509',
 '002510',
 '002511',
 '002512',
 '002513',
 '002514',
 '002515',
 '002516',
 '002517',
 '002518',
 '002519',
 '002520',
 '002521',
 '002522',
 '002523',
 '002524',
 '002526',
 '002527',
 '002528',
 '002529',
 '002530',
 '002531',
 '002532',
 '002533',
 '002534',
 '002535',
 '002536',
 '002537',
 '002538',
 ...]

In [36]:
candles = qa.QA_fetch_stock_day_adv('300482', start = '2018-01-01', end='2018-07-13')
candles.data.tail(10)

,,code,open,high,low,close,volume,amount,date,high_limit,low_limit,next_day_high_limit,next_day_low_limit
date,code,,,,,,,,,,,,
2018-07-02,300482,300482,69.89,71.93,69.27,70.20,15182.0,107423328.0,2018-07-02,77.00,63.00,77.22,63.18
2018-07-03,300482,300482,70.37,71.80,68.66,71.01,8949.0,63020736.0,2018-07-03,77.22,63.18,78.11,63.91
2018-07-04,300482,300482,70.51,71.77,69.83,70.14,10114.0,71387176.0,2018-07-04,78.11,63.91,77.15,63.13
2018-07-05,300482,300482,70.04,70.14,66.56,66.60,10042.0,68323344.0,2018-07-05,77.15,63.13,73.26,59.94
2018-07-06,300482,300482,67.46,70.44,66.50,67.02,14211.0,97182664.0,2018-07-06,73.26,59.94,73.72,60.32
2018-07-09,300482,300482,67.80,71.60,67.22,71.35,15044.0,104877008.0,2018-07-09,73.72,60.32,78.49,64.22
2018-07-10,300482,300482,71.78,73.50,70.45,72.98,18454.0,133643440.0,2018-07-10,78.49,64.22,80.28,65.68
2018-07-11,300482,300482,71.62,74.30,71.04,73.90,14637.0,106903928.0,2018-07-11,80.28,65.68,81.29,66.51
2018-07-12,300482,300482,73.61,75.88,73.10,74.90,16655.0,124481152.0,2018-07-12,81.29,66.51,82.39,67.41
2018-07-13,300482,300482,42.16,44.95,41.33,43.90,55461.0,240964032.0,2018-07-13,82.39,67.41,48.29,39.51

In [4]:
da = candles.data
da['rh'] = da.high.rolling(50).max()

In [5]:
da['rl'] = da.low.rolling(50).min()

In [6]:
da.tail(20)

,,code,open,high,low,close,volume,amount,date,high_limit,low_limit,next_day_high_limit,next_day_low_limit,rh,rl
date,code,,,,,,,,,,,,,,
2018-06-15,000713,000713,5.78,6.09,5.68,5.94,62766.0,36706404.0,2018-06-15,6.31,5.17,6.53,5.35,7.77,5.68
2018-06-19,000713,000713,6.21,6.53,6.21,6.53,321264.0,208486928.0,2018-06-19,6.53,5.35,7.18,5.88,7.77,5.68
2018-06-20,000713,000713,6.40,6.43,5.90,6.26,237230.0,147345552.0,2018-06-20,7.18,5.88,6.89,5.63,7.77,5.68
2018-06-21,000713,000713,6.06,6.39,6.05,6.10,153442.0,94997120.0,2018-06-21,6.89,5.63,6.71,5.49,7.77,5.68
2018-06-22,000713,000713,5.92,6.11,5.49,6.04,147373.0,85216032.0,2018-06-22,6.71,5.49,6.64,5.44,7.77,5.49
2018-06-25,000713,000713,5.92,6.38,5.87,6.17,135889.0,82252872.0,2018-06-25,6.64,5.44,6.79,5.55,7.77,5.49
2018-06-26,000713,000713,5.99,6.27,5.93,6.11,105746.0,64389848.0,2018-06-26,6.79,5.55,6.72,5.50,7.77,5.49
2018-06-27,000713,000713,6.10,6.20,6.00,6.08,93857.0,57123052.0,2018-06-27,6.72,5.50,6.69,5.47,7.77,5.49
2018-06-28,000713,000713,6.00,6.11,5.71,5.74,101304.0,60228288.0,2018-06-28,6.69,5.47,6.31,5.17,7.77,5.49
2018-06-29,000713,000713,5.78,5.96,5.73,5.91,76884.0,44998024.0,2018-06-29,6.31,5.17,6.50,5.32,7.77,5.49
2018-07-02,000713,000713,5.96,6.41,5.92,6.15,161916.0,99541936.0,2018-07-02,6.50,5.32,6.77,5.54,7.77,5.49
2018-07-03,000713,000713,6.26,6.30,6.08,6.28,133603.0,82953208.0,2018-07-03,6.77,5.54,6.91,5.65,7.77,5.49
2018-07-04,000713,000713,6.26,6.80,6.18,6.60,199634.0,129594800.0,2018-07-04,6.91,5.65,7.26,5.94,7.77,5.49
2018-07-05,000713,000713,6.47,6.75,6.34,6.49,177169.0,115544656.0,2018-07-05,7.26,5.94,7.14,5.84,7.77,5.49
2018-07-06,000713,000713,6.54,7.14,6.27,7.14,302808.0,204778352.0,2018-07-06,7.14,5.84,7.85,6.43,7.77,5.49
2018-07-09,000713,000713,6.86,7.45,6.81,7.15,307205.0,217256224.0,2018-07-09,7.85,6.43,7.87,6.44,7.77,5.49
2018-07-10,000713,000713,7.00,7.12,6.91,6.99,178447.0,124942264.0,2018-07-10,7.87,6.44,7.69,6.29,7.77,5.49
2018-07-11,000713,000713,6.90,7.39,6.89,7.04,283350.0,202317744.0,2018-07-11,7.69,6.29,7.74,6.34,7.77,5.49
2018-07-12,000713,000713,6.85,7.14,6.70,7.03,216007.0,149474704.0,2018-07-12,7.74,6.34,7.73,6.33,7.77,5.49
2018-07-13,000713,000713,6.91,6.95,6.77,6.78,135077.0,92503520.0,2018-07-13,7.73,6.33,7.46,6.10,7.77,5.49

In [17]:
def double_digits(nin):
    ps = str(nin).replace('.', '')
    r1 = re.search(r'(\d)\1$', ps)
    r2 = re.search(r'(\d{2})\1', ps)
    # r3 = re.search(r'(\d)\1$', ps)
    return True if r1 or r2 else False
    
double_digits(55.77)

True

In [18]:
mh = da.high.apply(double_digits) & (da.high == da.rh)
da.loc[mh, :]

,,code,open,high,low,close,volume,amount,date,high_limit,low_limit,next_day_high_limit,next_day_low_limit,rh,rl
date,code,,,,,,,,,,,,,,
2015-06-11,000713,000713,18.51,20.11,18.51,19.92,256327.0,494157856.0,2015-06-11,20.54,16.80,21.91,17.93,20.11,12.24
2015-11-25,000713,000713,12.28,12.66,12.20,12.56,144140.0,178790784.0,2015-11-25,13.48,11.03,13.82,11.30,12.66,8.07
2016-04-05,000713,000713,10.37,10.66,10.25,10.42,195380.0,203252976.0,2016-04-05,11.36,9.30,11.46,9.38,10.66,8.33
2016-04-13,000713,000713,10.66,11.11,10.66,10.85,131046.0,143525504.0,2016-04-13,11.76,9.62,11.94,9.77,11.11,8.33
2016-04-14,000713,000713,10.95,11.33,10.87,11.30,110408.0,122671528.0,2016-04-14,11.94,9.77,12.43,10.17,11.33,8.33
2016-04-15,000713,000713,11.34,11.44,11.09,11.30,83774.0,94210616.0,2016-04-15,12.43,10.17,12.43,10.17,11.44,8.33
2016-11-08,000713,000713,11.97,12.11,11.81,11.88,78140.0,93481312.0,2016-11-08,13.07,10.69,13.07,10.69,12.11,10.60
2017-09-13,000713,000713,8.36,8.80,8.32,8.52,72202.0,61715188.0,2017-09-13,9.22,7.54,9.37,7.67,8.80,7.50
2018-03-26,000713,000713,7.60,7.77,7.16,7.32,348043.0,260536576.0,2018-03-26,8.01,6.55,8.05,6.59,7.77,5.50

In [21]:
lh = da.low.apply(double_digits) & (da.low == da.rl)
da.loc[mh | lh, :]

,,code,open,high,low,close,volume,amount,date,high_limit,low_limit,next_day_high_limit,next_day_low_limit,rh,rl
date,code,,,,,,,,,,,,,,
2015-06-11,000713,000713,18.51,20.11,18.51,19.92,256327.0,494157856.0,2015-06-11,20.54,16.80,21.91,17.93,20.11,12.24
2015-07-08,000713,000713,7.88,8.31,7.88,7.88,198887.0,157976016.0,2015-07-08,9.63,7.88,8.67,7.09,21.87,7.88
2015-11-25,000713,000713,12.28,12.66,12.20,12.56,144140.0,178790784.0,2015-11-25,13.48,11.03,13.82,11.30,12.66,8.07
2016-01-08,000713,000713,11.01,11.47,10.22,10.93,98938.0,108139992.0,2016-01-08,12.10,9.90,12.02,9.84,14.00,10.22
2016-01-14,000713,000713,8.89,9.60,8.80,9.51,44164.0,40881544.0,2016-01-14,10.18,8.33,10.46,8.56,14.00,8.80
2016-01-18,000713,000713,8.83,9.34,8.80,9.10,50114.0,46075244.0,2016-01-18,9.98,8.16,10.01,8.19,14.00,8.80
2016-02-29,000713,000713,9.16,9.19,8.33,8.60,71414.0,62476264.0,2016-02-29,10.19,8.33,9.46,7.74,14.00,8.33
2016-04-05,000713,000713,10.37,10.66,10.25,10.42,195380.0,203252976.0,2016-04-05,11.36,9.30,11.46,9.38,10.66,8.33
2016-04-13,000713,000713,10.66,11.11,10.66,10.85,131046.0,143525504.0,2016-04-13,11.76,9.62,11.94,9.77,11.11,8.33
2016-04-14,000713,000713,10.95,11.33,10.87,11.30,110408.0,122671528.0,2016-04-14,11.94,9.77,12.43,10.17,11.33,8.33
2016-04-15,000713,000713,11.34,11.44,11.09,11.30,83774.0,94210616.0,2016-04-15,12.43,10.17,12.43,10.17,11.44,8.33
2016-11-08,000713,000713,11.97,12.11,11.81,11.88,78140.0,93481312.0,2016-11-08,13.07,10.69,13.07,10.69,12.11,10.60
2017-04-19,000713,000713,9.49,9.52,9.22,9.31,42315.0,39386388.0,2017-04-19,10.47,8.57,10.24,8.38,11.14,9.22
2017-09-13,000713,000713,8.36,8.80,8.32,8.52,72202.0,61715188.0,2017-09-13,9.22,7.54,9.37,7.67,8.80,7.50
2017-11-02,000713,000713,7.79,7.83,7.55,7.64,31601.0,24241332.0,2017-11-02,8.60,7.04,8.40,6.88,8.86,7.55
2018-02-06,000713,000713,5.99,6.00,5.50,5.62,41871.0,24355500.0,2018-02-06,6.72,5.50,6.18,5.06,7.65,5.50
2018-03-26,000713,000713,7.60,7.77,7.16,7.32,348043.0,260536576.0,2018-03-26,8.01,6.55,8.05,6.59,7.77,5.50

In [28]:
found = []
for stock in stocks:
    candles = qa.QA_fetch_stock_day_adv(stock, start = '2017-10-01', end='2018-07-13')
    if not candles:
        continue
    da = candles.data
    da['rh'] = da.high.rolling(50).max()
    da['rl'] = da.low.rolling(50).min()
    mh = da.high.apply(double_digits) & (da.high == da.rh)
    lh = da.low.apply(double_digits) & (da.low == da.rl)
    found.append(da.loc[mh | lh, :])
    
full = pd.concat(found, axis=0)

💢 Error QA_fetch_stock_day_adv parameter code=000511 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=000629 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=000950 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=600432 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=600806 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=601869 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None
💢 Error QA_fetch_stock_day_adv parameter code=603657 , start=2017-10-01, end=2018-07-13 call QA_fetch_stock_day return None

In [24]:
full.loc[full.date>'2018-06-15', :]

NotImplementedError: Indexing a MultiIndex with a DataFrame key is not implemented

In [29]:
full.head()

,,code,open,high,low,close,volume,amount,date,high_limit,low_limit,next_day_high_limit,next_day_low_limit,rh,rl
date,code,,,,,,,,,,,,,,
2018-03-29,000001,000001,10.92,11.17,10.55,11.05,1330602.0,1.445282e+09,2018-03-29,11.98,9.80,12.16,9.95,15.13,10.55
2018-06-11,000001,000001,10.06,10.13,10.00,10.04,721374.0,7.246880e+08,2018-06-11,11.13,9.11,11.04,9.04,11.94,10.00
2018-07-02,000001,000001,9.05,9.05,8.55,8.61,1315520.0,1.158546e+09,2018-07-02,10.00,8.18,9.47,7.75,11.94,8.55
2018-01-05,000002,000002,32.98,35.88,32.80,34.76,843101.0,2.916788e+09,2018-01-05,36.43,29.81,38.24,31.28,35.88,26.70
2018-02-09,000005,000005,3.68,3.69,3.55,3.64,41587.0,1.507601e+07,2018-02-09,4.08,3.34,4.00,3.28,4.55,3.55

In [32]:
fs = full.reset_index(drop=True)
fs['hh'] = fs.high == fs.rh
fs['hl'] = fs.low == fs.rl
fh = fs.loc[fs.date>'2018-07-05',['date','code','hh', 'hl','high', 'low']]
fh

           date    code     hh     hl    high     low
117  2018-07-11  000158  False   True    6.30    5.77
140  2018-07-13  000409  False   True    3.42    3.11
157  2018-07-06  000420  False   True    2.47    2.33
159  2018-07-06  000421  False   True    4.62    4.44
177  2018-07-06  000505  False   True    6.03    5.55
179  2018-07-06  000507  False   True    8.18    7.70
193  2018-07-11  000523  False   True    6.25    5.77
213  2018-07-06  000536  False   True    2.67    2.55
214  2018-07-11  000536  False   True    2.65    2.55
238  2018-07-11  000548  False   True    4.14    3.99
269  2018-07-09  000576  False   True   12.66   12.66
290  2018-07-13  000596   True  False   99.66   90.23
344  2018-07-06  000627  False   True    6.83    6.60
345  2018-07-11  000627  False   True    6.73    6.33
369  2018-07-13  000650   True  False    7.99    7.53
381  2018-07-12  000661   True  False  250.88  239.08
404  2018-07-09  000676  False   True   11.00   10.55
452  2018-07-06  000710  False   True   49.00   47.22
461  2018-07-06  000716  False   True    3.46    3.33
465  2018-07-06  000718  False   True    3.59    3.44
492  2018-07-09  000736  False   True   10.17    9.90
577  2018-07-06  000811  False   True    4.78    4.55
578  2018-07-11  000811  False   True    4.71    4.55
605  2018-07-06  000835  False   True    4.61    4.44
635  2018-07-13  000860   True  False   43.55   40.30
658  2018-07-11  000888  False   True    8.09    7.66
684  2018-07-06  000913  False   True   11.80   11.11
693  2018-07-06  000918  False   True    4.34    4.11
749  2018-07-12  000960  False   True   10.94   10.33
815  2018-07-06  000998  False   True   18.57   16.88
...         ...     ...    ...    ...     ...     ...
6030 2018-07-11  603111  False   True    6.58    6.33
6037 2018-07-06  603117  False   True    6.62    6.33
6043 2018-07-06  603133  False   True   19.48   18.77
6062 2018-07-06  603161  False   True   21.10   20.00
6067 2018-07-06  603167  False   True    9.09    8.80
6074 2018-07-06  603179  False   True   20.80   19.90
6122 2018-07-06  603233  False   True   60.66   56.33
6152 2018-07-06  603300  False   True    5.09    4.77
6173 2018-07-06  603318  False   True   12.33   11.77
6211 2018-07-12  603360  False   True   13.56   13.11
6241 2018-07-06  603385  False   True   10.45   10.11
6242 2018-07-11  603385  False   True   10.50   10.11
6264 2018-07-09  603456  False   True    7.65    7.11
6290 2018-07-06  603508   True  False   41.99   37.51
6303 2018-07-11  603519  False   True    7.87    7.33
6313 2018-07-09  603538  False   True   15.14   14.77
6316 2018-07-06  603555  False   True   10.79   10.00
6336 2018-07-06  603577  False   True   10.83   10.11
6342 2018-07-12  603579  False   True   68.39   63.55
6344 2018-07-06  603580  False   True   16.78   15.88
6366 2018-07-10  603602  False   True   34.33   28.80
6384 2018-07-12  603612  False   True   20.22   18.80
6406 2018-07-11  603628  False   True    9.94    9.33
6421 2018-07-06  603655  False   True   21.10   19.88
6459 2018-07-13  603678   True  False   28.11   26.50
6475 2018-07-13  603690   True  False   26.77   24.00
6476 2018-07-13  603696  False   True   21.64   19.77
6617 2018-07-13  603886   True  False   22.20   20.40
6659 2018-07-06  603926  False   True   17.75   16.55
6723 2018-07-06  603998  False   True    7.76    7.11

[219 rows x 6 columns]

In [38]:
fh = fs.loc[fs.date>'2018-07-05',['date','code','hh', 'hl','high', 'low']]
fh.loc[fh.hl, :].sort_values('date')

           date    code     hh    hl   high    low
6723 2018-07-06  603998  False  True   7.76   7.11
3875 2018-07-06  300665  False  True  13.10  12.20
5665 2018-07-06  601222  False  True   4.81   4.55
3712 2018-07-06  300587  False  True  18.46  17.17
3497 2018-07-06  300485  False  True  13.88  12.33
6659 2018-07-06  603926  False  True  17.75  16.55
5701 2018-07-06  601366  False  True   8.97   8.55
3304 2018-07-06  300382  False  True   6.84   6.44
3264 2018-07-06  300355  False  True   5.82   5.50
3103 2018-07-06  300289  False  True   6.22   5.88
5742 2018-07-06  601600  False  True   3.48   3.33
2923 2018-07-06  300202  False  True  10.38   9.55
2893 2018-07-06  300181  False  True   5.06   4.88
2889 2018-07-06  300179  False  True   4.43   4.11
3909 2018-07-06  300682  False  True  20.68  19.11
5832 2018-07-06  601898  False  True   4.61   4.40
2663 2018-07-06  300063  False  True   3.26   3.11
2641 2018-07-06  300054  False  True   8.26   7.55
2509 2018-07-06  002900  False  True  16.35  15.50
2472 2018-07-06  002879  False  True  16.00  14.77
2449 2018-07-06  002867  False  True  28.58  26.55
5938 2018-07-06  603021  False  True   6.62   6.11
5291 2018-07-06  600774  False  True  10.79  10.00
2336 2018-07-06  002812  False  True  44.89  39.99
2298 2018-07-06  002793  False  True  12.68  12.11
2279 2018-07-06  002781  False  True  15.42  14.77
2143 2018-07-06  002701  False  True   5.60   5.11
2127 2018-07-06  002695  False  True  13.17  11.88
5990 2018-07-06  603079  False  True  28.12  26.11
2826 2018-07-06  300143  False  True  11.54  10.00
...         ...     ...    ...   ...    ...    ...
193  2018-07-11  000523  False  True   6.25   5.77
4878 2018-07-11  600529  False  True  17.88  17.33
4763 2018-07-11  600463  False  True   7.08   6.66
4640 2018-07-11  600383  False  True   9.00   8.66
4595 2018-07-11  600356  False  True   6.11   5.77
214  2018-07-11  000536  False  True   2.65   2.55
2849 2018-07-11  300158  False  True   4.87   4.55
238  2018-07-11  000548  False  True   4.14   3.99
4202 2018-07-11  600115  False  True   6.29   5.88
4169 2018-07-11  600097  False  True  10.50  10.00
3862 2018-07-11  300660  False  True  25.10  23.77
3345 2018-07-11  300406  False  True  13.27  12.55
345  2018-07-11  000627  False  True   6.73   6.33
4271 2018-07-11  600172  False  True   4.08   3.88
1121 2018-07-11  002170  False  True   3.32   3.22
6384 2018-07-12  603612  False  True  20.22  18.80
6342 2018-07-12  603579  False  True  68.39  63.55
2014 2018-07-12  002641  False  True   3.49   3.33
6211 2018-07-12  603360  False  True  13.56  13.11
3149 2018-07-12  300306  False  True   8.43   7.88
4341 2018-07-12  600203  False  True   7.66   7.66
4416 2018-07-12  600247  False  True   4.74   4.40
5080 2018-07-12  600654  False  True   2.28   2.20
749  2018-07-12  000960  False  True  10.94  10.33
2680 2018-07-13  300072  False  True  19.00  18.55
3051 2018-07-13  300266  False  True   5.93   5.66
4632 2018-07-13  600377  False  True   8.96   8.66
140  2018-07-13  000409  False  True   3.42   3.11
6476 2018-07-13  603696  False  True  21.64  19.77
3489 2018-07-13  300482  False  True  44.95  41.33

[197 rows x 6 columns]

In [39]:
fh.to_excel('d:/Software/doubledigits.xls')